Base:
    model_root: './checkpoints/'
    num_workers: 10
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null
    vq_num_embeddings: 32

deepfm_default: # This is a config template
    model: DeepFM
    dataset_id: criteo_x1_default
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    hidden_units: [300, 300, 300]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 0
    learning_rate: 1.e-3
    batch_norm: False
    net_dropout: 0
    batch_size: 10000
    embedding_dim: 40
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

fm_default: # This is a config template
    model: FM
    dataset_id: criteo_x1_default
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

ffm_default: # This is a config template
    model: FFM
    dataset_id: criteo_x1_default
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    regularizer: 0
    batch_size: 10000
    embedding_dim: 2
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

ffmv2_default: # This is a config template
    model: FFMv2
    dataset_id: criteo_x1_default
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    regularizer: 0
    batch_size: 10000
    embedding_dim: 2
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    trans_embedding_dim: False

dcnv2_default: # This is a config template
    model: DCNv2
    dataset_id: criteo_x1_default
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: parallel
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    stacked_dnn_hidden_units: [500, 500, 500]
    parallel_dnn_hidden_units: [500, 500, 500]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'